<div class="toppanel"></div>

    <div class="panel">
        <div class="leftside">

            <div class="loginpanel">
                <h2>Mijn Portfolio</h2>
                Sinds ik werkzaam ben als ontwikkelaar heb ik meegewerkt aan tal van 
                websites en webapplicaties. Meestal in een bedrijf en als 
                onderdeel van projectgroep, ik vind het dan ook niet netjes om
                openbaar met de veren te pronken. Om die reden staat het overzicht 
                achter een login verstopt. Geïnteresseerd? Laat het me weten per e-mail (erik AT dit domein)
                <br/><br/>
            
        <?= $this->form ?>

        <?= $this->message ?>
            </div>

        </div>
        
    </div>            